# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Pu-Chin Chen
tagline:             'M.S. Computer Science @ UCLA'
description:         'Born in Taipei, Taiwan.<br>Studying in Los Angeles now.<br><br>Share what I saw and experienced in the United States.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            1
excerpt_separator:  '<!-- more -->'

# About/contact
author:
  name:              Pu-Chin Chen
  url:               https://michaelchen.github.io
  email:             puching110@gmail.com
  gravatar_md5:      2089b63e10c8c2e2af39df77ef525622

# Custom vars
version:             1.0.0

# Gems
plugins: [jekyll-paginate]
paginate_path: "page:num"

future: false

